repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.8.3
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [pre-push]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.8
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        files: ^(jobapppy/|tests/)
        additional_dependencies:
          - "pydantic[email]>=2.5.3,<3.0.0"
          - "types-PyYAML>=6.0.12"
