name: Release
on:
  release:
    types: [published]

jobs:
  build:
    name: Poetry build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-in-project: true
      - run: poetry install --no-interaction
      - run: poetry build
      - run: poetry run pytest

  publish_pypi:
    name: Publish (PyPI)
    needs: build
    runs-on: ubuntu-latest
    environment: 
      name: pypi-prod
      url: https://pypi.org/project/jobapppy/
    steps:
      - uses: actions/checkout@v4
      - name: Set up python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-in-project: true
      - run: poetry install --no-interaction
      - run: poetry build
      - run: poetry publish
      